### ISSUE TITLE
Windows (8?) error

### ISSUE THREAD

**Issue by bootsa** [Bristol-Braille/canute-ui#3] opened 2015-08-12 15:41 UTC
A user on Windows 8 gets error:
hardware_emulator.py, line 37,
self.process=subprocess.Popen(['/gui/display.py'])

returns:
WindowsErro 193 %1 is not a valid application.

**Comment by mattvenn** [comment] 2015-08-13 08:21
That's because this line in hardware_emulator.py

self.process = subprocess.Popen(["./gui_display.py"])

./gui_display.py is correct for unix but maybe not for windows. If anyone
has a windows install and wants to try changing the name of the program
(maybe remove the ./ ?). Let me know what works and I'll include the change.


On 12 August 2015 at 16:41, Steph <notifications@github.com> wrote:

> A user on Windows 8 gets error:
> hardware_emulator.py, line 37,
> self.process=subprocess.Popen(['/gui/display.py'])
>
> returns:
> WindowsErro 193 %1 is not a valid application.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bristol-Braille/canute-ui/issues/3>.
>



-- 
Matthew Venn
mattvenn.net

**Comment by ArmanArbab** [comment] 2016-06-20 09:26
Based on what I read here: http://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application
I did the following, which fixed the "WindowsErro 193 %1 is not a valid application." error. in driver_emulated.py I added "import sys" to the import statements, and I changed line 42 to read " process = [sys.executable, "./qt_display.py" ]". 

However, though I no longer receive the "WindowsErro 193 %1 is not a valid application" error message, and though I have installed PySide, I get the following error message when launching ui.py, and the gui never appears (I will include the important part of the error message first, then the full error message below):

Important part: 
Traceback (most recent call last):
  File "./qt_display.py", line 149, in <module>
    main()
  File "./qt_display.py", line 36, in main
    display = Display(display_text=args.text)
  File "./qt_display.py", line 75, in __init__
    self.udp_recv = udp_recv(port=5000)
  File "C:\Users\arman\workspace\Canute\root\ui\udp_utility.py", line 40, in __init__
    self.sock.bind((UDP_IP, self.port))
  File "C:\Program Files\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

Full error message:
2016-06-20 02:13:28,454 - buttons_config   - INFO     - config OK
2016-06-20 02:13:28,486 - root             - INFO     - running with emulated hardware
2016-06-20 02:13:28,882 - driver           - INFO     - device ready with 32 x 8 characters
2016-06-20 02:13:29,424 - driver_emulated  - INFO     - started qt_display.py with process id 3424
2016-06-20 02:13:29,523 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\about ncbi word g1.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:29,525 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:29,525 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\about ncbi word g1.pef
2016-06-20 02:13:30,028 - pageable         - INFO     - pef loaded with 300 lines
2016-06-20 02:13:30,029 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksabout ncbi word g1.canute]
2016-06-20 02:13:30,059 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:30,167 - pageable         - INFO     - adding new book [about ncbi word g1] to library
2016-06-20 02:13:30,174 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\about ncbi word g2.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:30,176 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:30,176 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\about ncbi word g2.pef
2016-06-20 02:13:30,207 - pageable         - INFO     - pef loaded with 244 lines
2016-06-20 02:13:30,207 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksabout ncbi word g2.canute]
2016-06-20 02:13:30,229 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:30,230 - pageable         - INFO     - adding new book [about ncbi word g2] to library
2016-06-20 02:13:30,233 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 A Study in Scarlet.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:30,233 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:30,234 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 A Study in Scarlet.pef
2016-06-20 02:13:31,229 - pageable         - INFO     - pef loaded with 8992 lines
2016-06-20 02:13:31,229 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 A Study in Scarlet.canute]
2016-06-20 02:13:31,279 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:31,282 - pageable         - INFO     - adding new book [g2 A Study in Scarlet] to library
2016-06-20 02:13:31,288 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 AESOP'S FABLES.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:31,288 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:31,288 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 AESOP'S FABLES.pef
2016-06-20 02:13:32,290 - pageable         - INFO     - pef loaded with 7648 lines
2016-06-20 02:13:32,292 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 AESOP'S FABLES.canute]
2016-06-20 02:13:32,483 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:32,487 - pageable         - INFO     - adding new book [g2 AESOP'S FABLES] to library
2016-06-20 02:13:32,493 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 Andersen's Fairy Tales.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:32,493 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:32,493 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 Andersen's Fairy Tales.pef
2016-06-20 02:13:33,923 - pageable         - INFO     - pef loaded with 10484 lines
2016-06-20 02:13:33,923 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 Andersen's Fairy Tales.canute]
2016-06-20 02:13:33,982 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:33,986 - pageable         - INFO     - adding new book [g2 Andersen's Fairy Tales] to library
2016-06-20 02:13:33,992 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 Dracula.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:33,992 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:33,992 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 Dracula.pef
2016-06-20 02:13:37,492 - pageable         - INFO     - pef loaded with 28580 lines
2016-06-20 02:13:37,493 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 Dracula.canute]
2016-06-20 02:13:37,614 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:37,625 - pageable         - INFO     - adding new book [g2 Dracula] to library
2016-06-20 02:13:37,631 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 Fall of House of Usher.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:37,631 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:37,631 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 Fall of House of Usher.pef
2016-06-20 02:13:37,898 - pageable         - INFO     - pef loaded with 2132 lines
2016-06-20 02:13:37,898 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 Fall of House of Usher.canute]
2016-06-20 02:13:37,913 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:37,914 - pageable         - INFO     - adding new book [g2 Fall of House of Usher] to library
INFO:__main__:display GUI
2016-06-20 02:13:38,040 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 Rime of Ancient Mariner.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:38,042 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:38,042 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 Rime of Ancient Mariner.pef
Traceback (most recent call last):
  File "./qt_display.py", line 149, in <module>
    main()
  File "./qt_display.py", line 36, in main
    display = Display(display_text=args.text)
  File "./qt_display.py", line 75, in __init__
    self.udp_recv = udp_recv(port=5000)
  File "C:\Users\arman\workspace\Canute\root\ui\udp_utility.py", line 40, in __init__
    self.sock.bind((UDP_IP, self.port))
  File "C:\Program Files\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
2016-06-20 02:13:38,545 - pageable         - INFO     - pef loaded with 1676 lines
2016-06-20 02:13:38,545 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 Rime of Ancient Mariner.canute]
2016-06-20 02:13:38,556 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:38,559 - pageable         - INFO     - adding new book [g2 Rime of Ancient Mariner] to library
2016-06-20 02:13:38,563 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 The Jungle Book.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:38,563 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:38,563 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 The Jungle Book.pef
2016-06-20 02:13:39,723 - pageable         - INFO     - pef loaded with 10040 lines
2016-06-20 02:13:39,724 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 The Jungle Book.canute]
2016-06-20 02:13:39,775 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:39,779 - pageable         - INFO     - adding new book [g2 The Jungle Book] to library
2016-06-20 02:13:39,808 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\g2 the time machine.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:39,808 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:39,808 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\g2 the time machine.pef
2016-06-20 02:13:40,494 - pageable         - INFO     - pef loaded with 6508 lines
2016-06-20 02:13:40,494 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksg2 the time machine.canute]
2016-06-20 02:13:40,526 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:40,529 - pageable         - INFO     - adding new book [g2 the time machine] to library
2016-06-20 02:13:40,533 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\ncbi news summer 2015 g1.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:40,533 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:40,535 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\ncbi news summer 2015 g1.pef
2016-06-20 02:13:40,740 - pageable         - INFO     - pef loaded with 2960 lines
2016-06-20 02:13:40,742 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksncbi news summer 2015 g1.canute]
2016-06-20 02:13:40,759 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:40,760 - pageable         - INFO     - adding new book [ncbi news summer 2015 g1] to library
2016-06-20 02:13:40,765 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\ncbi news summer 2015 g2.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:40,766 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:40,766 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\ncbi news summer 2015 g2.pef
2016-06-20 02:13:40,950 - pageable         - INFO     - pef loaded with 2304 lines
2016-06-20 02:13:40,950 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksncbi news summer 2015 g2.canute]
2016-06-20 02:13:41,007 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:41,010 - pageable         - INFO     - adding new book [ncbi news summer 2015 g2] to library
2016-06-20 02:13:41,065 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\ncbi services v5 g1.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:41,066 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:41,066 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\ncbi services v5 g1.pef
2016-06-20 02:13:41,085 - pageable         - INFO     - pef loaded with 256 lines
2016-06-20 02:13:41,085 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksncbi services v5 g1.canute]
2016-06-20 02:13:41,092 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:41,092 - pageable         - INFO     - adding new book [ncbi services v5 g1] to library
2016-06-20 02:13:41,098 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\ncbi services v5 g2.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:41,098 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:41,098 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\ncbi services v5 g2.pef
2016-06-20 02:13:41,117 - pageable         - INFO     - pef loaded with 236 lines
2016-06-20 02:13:41,117 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksncbi services v5 g2.canute]
2016-06-20 02:13:41,150 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:41,151 - pageable         - INFO     - adding new book [ncbi services v5 g2] to library
2016-06-20 02:13:41,155 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc A Study in Scarlet.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:41,155 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:41,155 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc A Study in Scarlet.pef
2016-06-20 02:13:41,802 - pageable         - ERROR    - could not convert C:\Users\arman\workspace\Canute\root\books\uc A Study in Scarlet.pef
2016-06-20 02:13:41,802 - pageable         - INFO     - adding new book [uc A Study in Scarlet] to library
2016-06-20 02:13:41,809 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc AESOP'S FABLES.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:41,809 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:41,809 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc AESOP'S FABLES.pef
2016-06-20 02:13:42,783 - pageable         - INFO     - pef loaded with 9912 lines
2016-06-20 02:13:42,785 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc AESOP'S FABLES.canute]
2016-06-20 02:13:42,913 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:42,921 - pageable         - INFO     - adding new book [uc AESOP'S FABLES] to library
2016-06-20 02:13:42,930 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc Andersen's Fairy Tales.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:42,930 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:42,930 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc Andersen's Fairy Tales.pef
2016-06-20 02:13:44,273 - pageable         - INFO     - pef loaded with 13916 lines
2016-06-20 02:13:44,273 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc Andersen's Fairy Tales.canute]
2016-06-20 02:13:44,335 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:44,342 - pageable         - INFO     - adding new book [uc Andersen's Fairy Tales] to library
2016-06-20 02:13:44,346 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc Dracula.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:44,348 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:44,348 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc Dracula.pef
2016-06-20 02:13:48,209 - pageable         - INFO     - pef loaded with 37308 lines
2016-06-20 02:13:48,209 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc Dracula.canute]
2016-06-20 02:13:48,382 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:48,404 - pageable         - INFO     - adding new book [uc Dracula] to library
2016-06-20 02:13:48,413 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc Fall of House of Usher.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:48,413 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:48,414 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc Fall of House of Usher.pef
2016-06-20 02:13:48,842 - pageable         - INFO     - pef loaded with 2736 lines
2016-06-20 02:13:48,842 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc Fall of House of Usher.canute]
2016-06-20 02:13:49,046 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:49,049 - pageable         - INFO     - adding new book [uc Fall of House of Usher] to library
2016-06-20 02:13:49,099 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc Rime of Ancient Mariner.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:49,101 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:49,101 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc Rime of Ancient Mariner.pef
2016-06-20 02:13:49,401 - pageable         - INFO     - pef loaded with 2120 lines
2016-06-20 02:13:49,401 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc Rime of Ancient Mariner.canute]
2016-06-20 02:13:49,415 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:49,417 - pageable         - INFO     - adding new book [uc Rime of Ancient Mariner] to library
2016-06-20 02:13:49,423 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc The Jungle Book.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:49,423 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:49,423 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc The Jungle Book.pef
2016-06-20 02:13:51,006 - pageable         - INFO     - pef loaded with 12920 lines
2016-06-20 02:13:51,006 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc The Jungle Book.canute]
2016-06-20 02:13:51,065 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:51,071 - pageable         - INFO     - adding new book [uc The Jungle Book] to library
2016-06-20 02:13:51,075 - pageable         - INFO     - found new book file C:\Users\arman\workspace\Canute\root\books\uc the time machine.pef in C:\Users\arman\workspace\Canute\root\books
2016-06-20 02:13:51,075 - pageable         - INFO     - converting pef to canute
2016-06-20 02:13:51,075 - pageable         - INFO     - converting pef C:\Users\arman\workspace\Canute\root\books\uc the time machine.pef
2016-06-20 02:13:51,924 - pageable         - INFO     - pef loaded with 8584 lines
2016-06-20 02:13:51,926 - pageable         - INFO     - writing to [C:\Users\arman\workspace\Canute\root\booksuc the time machine.canute]
2016-06-20 02:13:51,967 - pageable         - INFO     - removing old pef file
2016-06-20 02:13:51,971 - pageable         - INFO     - adding new book [uc the time machine] to library
2016-06-20 02:13:51,977 - pageable         - INFO     - library has 22 books available
2016-06-20 02:13:52,117 - root             - INFO     - starting in library mode
2016-06-20 02:13:52,117 - pageable         - INFO     - showing page 1 of 3 (lines 0 -> 8)
2016-06-20 02:13:52,130 - root             - INFO     - display updated
2016-06-20 02:13:52,130 - root             - INFO     - UI main loop ending
2016-06-20 02:13:52,130 - driver_emulated  - INFO     - done


Also of note is that when I run qt_display.py alone, I get the following error message:
INFO:__main__:display GUI
Traceback (most recent call last):
  File "C:\Users\arman\workspace\Canute\root\ui\qt_display.py", line 149, in <module>
    main()
  File "C:\Users\arman\workspace\Canute\root\ui\qt_display.py", line 36, in main
    display = Display(display_text=args.text)
  File "C:\Users\arman\workspace\Canute\root\ui\qt_display.py", line 75, in __init__
    self.udp_recv = udp_recv(port=5000)
  File "C:\Users\arman\workspace\Canute\root\ui\udp_utility.py", line 40, in __init__
    self.sock.bind((UDP_IP, self.port))
  File "C:\Program Files\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by ArmanArbab** [comment] 2016-06-20 21:34
Upon closing and reopening eclipse, and waiting a few minutes, I no longer get the errors with qt_display.py that I reproduced above. However, when after running many iterations of ui.py in a few minutes, the error message reappears. Reading this page: http://stackoverflow.com/questions/12362542/python-server-only-one-usage-of-each-socket-address-is-normally-permitted
Led me to try the following modifications to udp_utility.py:
In line 42, where " self.sock.bind((UDP_IP, self.port))" is, I added this line before line 42: "self.sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)"
I also added these imports:
 from socket import SOL_SOCKET
from socket import SO_REUSEADDR

This solves the error message "socket.error: [Errno 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted", but now, when running ui.py, I get:

2016-06-20 14:31:43,454 - buttons_config   - INFO     - config OK
2016-06-20 14:31:43,456 - root             - INFO     - running with emulated hardware
2016-06-20 14:31:43,786 - driver           - INFO     - device ready with 32 x 8 characters
2016-06-20 14:31:43,806 - root             - ERROR    - [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions
Traceback (most recent call last):
  File "C:\Users\arman\workspace\Canute\root\ui\ui.py", line 280, in <module>
    with Emulated(delay=args.delay, display_text=args.text) as driver:
  File "C:\Users\arman\workspace\Canute\root\ui\driver_emulated.py", line 39, in __init__
    self.udp_recv = udp_recv(port=5001)
  File "C:\Users\arman\workspace\Canute\root\ui\udp_utility.py", line 43, in __init__
    self.sock.bind((UDP_IP, self.port))
  File "C:\Program Files\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 10013] An attempt was made to access a socket in a way forbidden by its access permissions

I then went to this page: http://stackoverflow.com/questions/2778840/socket-error-errno-10013-an-attempt-was-made-to-access-a-socket-in-a-way-forb , where I read one user's comment: " 10
down vote
accepted
	

On Windows Vista/7, with UAC, administrator accounts run programs in unprivileged mode by default.

Programs must prompt for administrator access before they run as administrator, with the ever-so-familiar UAC dialog. Since Python scripts aren't directly executable, there's no "Run as Administrator" context menu option.

It's possible to use ctypes.windll.shell32.IsUserAnAdmin() to detect whether the script has admin access, and ShellExecuteEx with the 'runas' verb on python.exe, with sys.argv[0] as a parameter to prompt the UAC dialog if needed." I haven't been able to figure out how to implement ShellExecuteEX, so I guess this is where I am now...

**Comment by mattvenn** [comment] 2016-06-21 08:05
Sounds like you're getting closer - sorry it's been so much hard work for
you!
Does windows have the same kind of idea about port numbers that linux does?
Maybe changing the port number to something 'unprivileged' would solve it.

On 20 June 2016 at 23:34, ArmanArbab <notifications@github.com> wrote:

> Upon closing and reopening eclipse, and waiting a few minutes, I no longer
> get the errors with qt_display.py that I reproduced above. However, when
> after running many iterations of ui.py in a few minutes, the error message
> reappears. Reading this page:
> http://stackoverflow.com/questions/12362542/python-server-only-one-usage-of-each-socket-address-is-normally-permitted
> Led me to try the following modifications to udp_utility.py:
> In line 42, where " self.sock.bind((UDP_IP, self.port))" is, I added this
> line before line 42: "self.sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)"
> I also added these imports:
> from socket import SOL_SOCKET
> from socket import SO_REUSEADDR
>
> This solves the error message "socket.error: [Errno 10048] Only one usage
> of each socket address (protocol/network address/port) is normally
> permitted", but now, when running ui.py, I get:
>
> 2016-06-20 14:31:43,454 - buttons_config - INFO - config OK
> 2016-06-20 14:31:43,456 - root - INFO - running with emulated hardware
> 2016-06-20 14:31:43,786 - driver - INFO - device ready with 32 x 8
> characters
> 2016-06-20 14:31:43,806 - root - ERROR - [Errno 10013] An attempt was made
> to access a socket in a way forbidden by its access permissions
> Traceback (most recent call last):
> File "C:\Users\arman\workspace\Canute\root\ui\ui.py", line 280, in
> with Emulated(delay=args.delay, display_text=args.text) as driver:
> File "C:\Users\arman\workspace\Canute\root\ui\driver_emulated.py", line
> 39, in *init*
> self.udp_recv = udp_recv(port=5001)
> File "C:\Users\arman\workspace\Canute\root\ui\udp_utility.py", line 43, in
> *init*
> self.sock.bind((UDP_IP, self.port))
> File "C:\Program Files\Python27\lib\socket.py", line 228, in meth
> return getattr(self._sock,name)(*args)
> error: [Errno 10013] An attempt was made to access a socket in a way
> forbidden by its access permissions
>
> I then went to this page:
> http://stackoverflow.com/questions/2778840/socket-error-errno-10013-an-attempt-was-made-to-access-a-socket-in-a-way-forb
> , where I read one user's comment: " 10
> down vote
> accepted
>
> On Windows Vista/7, with UAC, administrator accounts run programs in
> unprivileged mode by default.
>
> Programs must prompt for administrator access before they run as
> administrator, with the ever-so-familiar UAC dialog. Since Python scripts
> aren't directly executable, there's no "Run as Administrator" context menu
> option.
>
> It's possible to use ctypes.windll.shell32.IsUserAnAdmin() to detect
> whether the script has admin access, and ShellExecuteEx with the 'runas'
> verb on python.exe, with sys.argv[0] as a parameter to prompt the UAC
> dialog if needed." I haven't been able to figure out how to implement
> ShellExecuteEX, so I guess this is where I am now...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Bristol-Braille/canute-ui/issues/3#issuecomment-227276745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAmtbDk-ZHYklDk6BLu_gAbgJ8Dq-IeJks5qNwd6gaJpZM4FqTAy>
> .
>



-- 
Matthew Venn
web mattvenn.net twitter @matthewvenn <https://twitter.com/matthewvenn>

**Comment by kasbah** [comment] 2016-06-21 12:40
@mattvenn Sorry we kind of veered of and started discussing this in #6. It seems the issue is that the emulator GUI does not shut down cleanly.

**Comment by kasbah** [comment] 2017-01-12 14:13
I don't think this is an issue any more besides what is being tracked in #6.

**Closed by kasbah** 2017-01-12 14:13 UTC
Labels: bug
