### ISSUE TITLE
Deleting bookmarks 

### ISSUE THREAD

**Issue by liamsmyth92** [Bristol-Braille/canute-ui#254] opened 2019-09-24 10:16 UTC
Deleting a bookmark is not currently documented. 

Is there a way of doing this from the UI? If there is, ignore, if there is not, could we look at adding this ahead of release?

**Comment by liamsmyth92** [comment] 2019-09-24 10:43
Could this be marked as a milestone for first release please? I am not able.

**Comment by zwbrbr** [comment] 2019-09-24 11:05
Duplicate of #212; see new comment there.

**Closed by zwbrbr** 2019-09-24 11:05 UTC
